name: Beszel Agent
description: Beszel Agent for monitoring Home Assistant www.beszel.dev
version: 0.8.0
slug: beszel_agent
advanced: true
host_network: true
init: false
options:
  port: 45876
  key:
  token:
  hub_url:
schema:
  port: int
  key: str
  token: str
  hub_url: str
startup: system
arch:
  - amd64
  - armhf
  - armv7
